language: python
python:
  - "2.7"
# command to install dependencies
virtualenv:
  system_site_packages: true

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

install: "pip install -r requirements.txt"

# command to run tests
script:
  - nosetests
